# Generated by Django 6.0.1 on 2026-01-30 20:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estimated_savings', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('motivation', models.CharField(max_length=255)),
                ('check_in_frequency', models.CharField(default='weekly', max_length=20)),
                ('financial_context', models.JSONField(blank=True, default=dict)),
                ('action_plan', models.TextField(help_text='Personalized behavioral plan for the upcoming savings period.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='financial_profile', to='users.user')),
            ],
        ),
        migrations.CreateModel(
            name='SavingsHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='savings_history', to='users.user')),
            ],
        ),
    ]
